//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirCargoSubDetail
    {
        public int AirCargoSubDetailID { get; set; }
        public string Hawb { get; set; }
        public string Marks { get; set; }
        public string Commodity { get; set; }
        public string Pcs { get; set; }
        public string Wt { get; set; }
        public string Vol { get; set; }
        public Nullable<int> ShipperID { get; set; }
        public Nullable<int> ConsigneeID { get; set; }
        public int AirCargoID { get; set; }
    
        public virtual SIPL_AirCargo SIPL_AirCargo { get; set; }
    }
}
