//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_ACTION_AUD
    {
        public long AuditId { get; set; }
        public decimal ActId { get; set; }
        public string ActName { get; set; }
        public string ActCaption { get; set; }
        public System.DateTime ActCreatedTs { get; set; }
        public Nullable<System.DateTime> ActUpdatedTs { get; set; }
        public Nullable<decimal> ActCreatedBy { get; set; }
        public Nullable<decimal> ActUpdatedBy { get; set; }
        public string AuditAction { get; set; }
        public System.DateTime AuditDate { get; set; }
        public string AuditUser { get; set; }
        public string AuditApp { get; set; }
    }
}
