//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_ACCOUNTREF
    {
        public int iId { get; set; }
        public string AC_ID { get; set; }
        public string AC_CODE { get; set; }
        public string AC_NAME { get; set; }
        public string AC_Description { get; set; }
        public string AC_Accountype { get; set; }
        public string AC_Classification { get; set; }
        public string AC_Environment { get; set; }
        public Nullable<int> prodt_svr_ID { get; set; }
        public string Prodt_SVR_Name { get; set; }
    }
}
