//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_CONTACT_ACCT_CAT_MAP
    {
        public decimal CamID { get; set; }
        public decimal AcyID { get; set; }
        public decimal ContactID { get; set; }
        public System.DateTime CamCreatedTs { get; set; }
        public Nullable<System.DateTime> Cam_UpdatedTs { get; set; }
        public Nullable<decimal> Cam_CreatedBy { get; set; }
        public Nullable<decimal> Cam_UpdatedBy { get; set; }
    }
}
