//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_CONTACT_SITE_MAP
    {
        public decimal CsmId { get; set; }
        public decimal SitId { get; set; }
        public int ContactID { get; set; }
        public decimal SitIdRefBy { get; set; }
        public System.DateTime CsmCreatedTs { get; set; }
        public decimal CsmCreatedBy { get; set; }
        public Nullable<System.DateTime> CsmUpdatedTs { get; set; }
        public Nullable<decimal> CsmUpdatedBy { get; set; }
        public Nullable<int> SFC_ID { get; set; }
    
        public virtual SIPL_Contact SIPL_Contact { get; set; }
        public virtual LG_SITE LG_SITE { get; set; }
        public virtual LG_SITE LG_SITE1 { get; set; }
    }
}
