//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_CONTACT_AUD
    {
        public long AuditId { get; set; }
        public decimal CntId { get; set; }
        public decimal DptId { get; set; }
        public decimal TtlId { get; set; }
        public decimal CntType { get; set; }
        public string CntFirstName { get; set; }
        public string CntMiddleName { get; set; }
        public string CntLastName { get; set; }
        public string CntEmail { get; set; }
        public Nullable<bool> CntStatus { get; set; }
        public string CntReason { get; set; }
        public System.DateTime CntCreatedTs { get; set; }
        public Nullable<System.DateTime> CntUpdatedTs { get; set; }
        public Nullable<decimal> CwtId { get; set; }
        public Nullable<decimal> CntCreatedBy { get; set; }
        public Nullable<decimal> CntUpdatedBy { get; set; }
        public string AuditAction { get; set; }
        public System.DateTime AuditDate { get; set; }
        public string AuditUser { get; set; }
        public string AuditApp { get; set; }
    }
}
