//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_COUNTRY_AUD
    {
        public long AuditId { get; set; }
        public decimal CryId { get; set; }
        public string CryName { get; set; }
        public string CryAbbrev { get; set; }
        public Nullable<bool> CryStatus { get; set; }
        public System.DateTime CryCreatedTs { get; set; }
        public Nullable<System.DateTime> CryUpdatedTs { get; set; }
        public Nullable<decimal> CryPhoneCode { get; set; }
        public Nullable<decimal> CryCreatedBy { get; set; }
        public Nullable<decimal> CryUpdatedBy { get; set; }
        public string AuditAction { get; set; }
        public System.DateTime AuditDate { get; set; }
        public string AuditUser { get; set; }
        public string AuditApp { get; set; }
    }
}
