//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_CONTRACT_RATE
    {
        public decimal ContractRateID { get; set; }
        public decimal ContractID { get; set; }
        public decimal CarrierID { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string ApplicableToService { get; set; }
        public Nullable<int> OriginCountryID { get; set; }
        public Nullable<int> DestinationCountryID { get; set; }
        public Nullable<int> OrignStateID { get; set; }
        public Nullable<int> DestinationStateID { get; set; }
        public Nullable<int> OriginCityID { get; set; }
        public Nullable<int> DestinationCityID { get; set; }
        public Nullable<int> OriginModeID { get; set; }
        public Nullable<int> DestinationModeID { get; set; }
        public Nullable<int> PortOfOriginID { get; set; }
        public Nullable<int> PortOfDischargeID { get; set; }
        public string Notes { get; set; }
        public string AMDNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
