//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_CONTACT_WORK_TYPE_AUD
    {
        public long AuditId { get; set; }
        public decimal CwtId { get; set; }
        public string CwtName { get; set; }
        public bool CwtStatus { get; set; }
        public System.DateTime CwtCreatedTs { get; set; }
        public decimal CwtCreatedBy { get; set; }
        public Nullable<System.DateTime> CwtUpdatedTs { get; set; }
        public Nullable<decimal> CwtUpdatedBy { get; set; }
        public string AuditAction { get; set; }
        public System.DateTime AuditDate { get; set; }
        public string AuditUser { get; set; }
        public string AuditApp { get; set; }
    }
}
