//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_CONTACT_SITE_MAP_AUD
    {
        public long AuditId { get; set; }
        public decimal CsmId { get; set; }
        public decimal SitId { get; set; }
        public int ContactID { get; set; }
        public decimal SitIdRefBy { get; set; }
        public System.DateTime CsmCreatedTs { get; set; }
        public decimal CsmCreatedBy { get; set; }
        public Nullable<System.DateTime> CsmUpdatedTs { get; set; }
        public Nullable<decimal> CsmUpdatedBy { get; set; }
        public string AuditAction { get; set; }
        public System.DateTime AuditDate { get; set; }
        public string AuditUser { get; set; }
        public string AuditApp { get; set; }
    }
}
