//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_Container_Category
    {
        public decimal CCID { get; set; }
        public string CCName { get; set; }
        public decimal CCCreatedBy { get; set; }
        public System.DateTime CCCreatedOn { get; set; }
        public Nullable<decimal> CCUpdatedBy { get; set; }
        public Nullable<System.DateTime> CCUpdatedOn { get; set; }
        public decimal MOSID { get; set; }
        public string CCCode { get; set; }
    }
}
