//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LG_DOCUMENTATION_STATUS
    {
       [Key]
        public int Dos_Id { get; set; }
        public string Dos_Name { get; set; }
        public string Dos_Desc { get; set; }
        public System.DateTime Dos_CreatedTs { get; set; }
        public Nullable<System.DateTime> Dos_UpdatedTs { get; set; }
        public Nullable<decimal> Dos_CreatedBy { get; set; }
        public Nullable<decimal> Dos_UpdatedBy { get; set; }
    }
}
