//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LG_DEPARTMENT_AUD
    {
        [Key]
        public long AuditId { get; set; }
        public decimal DptId { get; set; }
        public string DptName { get; set; }
        public Nullable<bool> DptStatus { get; set; }
        public System.DateTime DptCreatedTs { get; set; }
        public Nullable<System.DateTime> DptUpdatedTs { get; set; }
        public Nullable<decimal> DptCreatedBy { get; set; }
        public Nullable<decimal> DptUpdatedBy { get; set; }
        public string AuditAction { get; set; }
        public System.DateTime AuditDate { get; set; }
        public string AuditUser { get; set; }
        public string AuditApp { get; set; }
    }
}
