//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LG_DOCUMENTATION
    {
       [Key]
        public decimal Doc_Id { get; set; }
        public int DocumentCommonID { get; set; }
        public int Dos_Id { get; set; }
        public Nullable<System.DateTime> Doc_ReceiptDate { get; set; }
        public Nullable<bool> Doc_IS_AES_ITN_REQ { get; set; }
        public string Doc_AES_ITN { get; set; }
        public Nullable<System.DateTime> Doc_ReceiptBLInstructionDate { get; set; }
        public Nullable<System.DateTime> Doc_BLInstructionLineDate { get; set; }
        public Nullable<System.DateTime> Doc_DraftBLLineDate { get; set; }
        public Nullable<System.DateTime> Doc_DraftBLCustomerDate { get; set; }
        public Nullable<System.DateTime> Doc_DraftBLApprovalDate { get; set; }
        public Nullable<System.DateTime> Doc_ApprovedDraftBLToLineDate { get; set; }
        public Nullable<System.DateTime> Doc_BLReleaseAwaitedFromLineDate { get; set; }
        public System.DateTime Doc_CreatedTs { get; set; }
        public Nullable<System.DateTime> Doc_UpdatedTs { get; set; }
        public Nullable<decimal> Doc_CreatedBy { get; set; }
        public Nullable<decimal> Doc_UpdatedBy { get; set; }
        public Nullable<bool> Iscompleted { get; set; }
    }
}
