//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_DASHBOARD_DATA
    {
        public Nullable<int> EYTD { get; set; }
        public Nullable<int> EMTD { get; set; }
        public Nullable<int> EUPQU { get; set; }
        public Nullable<int> EUPQF { get; set; }
        public Nullable<int> QYTD { get; set; }
        public Nullable<int> QMTD { get; set; }
        public Nullable<int> QPAU { get; set; }
        public Nullable<int> QPAF { get; set; }
        public Nullable<int> QSAU { get; set; }
        public Nullable<int> QSAF { get; set; }
        public Nullable<int> QSBU { get; set; }
        public Nullable<int> QSBF { get; set; }
        public Nullable<int> BYTD { get; set; }
        public Nullable<int> BMTD { get; set; }
        public Nullable<int> BTDU { get; set; }
        public Nullable<int> BTDF { get; set; }
        public Nullable<int> BWLCU { get; set; }
        public Nullable<int> BWLCF { get; set; }
        public Nullable<int> BASCU { get; set; }
        public Nullable<int> BASCF { get; set; }
        public Nullable<int> TPFTU { get; set; }
        public Nullable<int> TPFTF { get; set; }
        public Nullable<int> TPDRU { get; set; }
        public Nullable<int> TPDRF { get; set; }
        public Nullable<int> TPMDU { get; set; }
        public Nullable<int> TPMDF { get; set; }
        public Nullable<int> TCCSU { get; set; }
        public Nullable<int> TCCSF { get; set; }
        public Nullable<int> ACTDUE { get; set; }
        public Nullable<int> TOTACT { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public long DashboardId { get; set; }
        public decimal SitId { get; set; }
    }
}
