//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LG_LOCATION_AUD
    {
       [Key]
        public long AuditId { get; set; }
        public decimal LcnId { get; set; }
        public Nullable<decimal> CntId { get; set; }
        public Nullable<decimal> TmzId { get; set; }
        public Nullable<decimal> CcyId { get; set; }
        public string LcnInstitutionName { get; set; }
        public string LcnContactRole { get; set; }
        public string LcnAddress1 { get; set; }
        public string LcnAddress2 { get; set; }
        public string LcnAddress3 { get; set; }
        public string LcnCity { get; set; }
        public string LcnPostalCode { get; set; }
        public string LcnForiegnProvince { get; set; }
        public Nullable<decimal> UstId { get; set; }
        public Nullable<decimal> CryId { get; set; }
        public string LcnLatitute { get; set; }
        public string LcnLongitude { get; set; }
        public string LcnPhone { get; set; }
        public string LcnPhoneExt { get; set; }
        public string LcnFax { get; set; }
        public string LcnMobilePhone { get; set; }
        public Nullable<bool> LcnStatus { get; set; }
        public string LcnReason { get; set; }
        public System.DateTime LcnCreatedTs { get; set; }
        public Nullable<System.DateTime> LcnUpdatedTs { get; set; }
        public Nullable<decimal> LcnCreatedBy { get; set; }
        public Nullable<decimal> LcnUpdatedBy { get; set; }
        public string AuditAction { get; set; }
        public System.DateTime AuditDate { get; set; }
        public string AuditUser { get; set; }
        public string AuditApp { get; set; }
    }
}
