//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LG_Mode_Of_Service
    {
       [Key]
        public decimal MOSID { get; set; }
        public string MOSName { get; set; }
        public decimal MOSCreatedBy { get; set; }
        public System.DateTime MOSCreatedOn { get; set; }
        public Nullable<decimal> MOSUpdatedBy { get; set; }
        public Nullable<System.DateTime> MOSUpdatedOn { get; set; }
    }
}
