//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LG_MAM_ROL_MAP_AUD
    {
        [Key]
        public long AuditId { get; set; }
        public decimal MrmId { get; set; }
        public decimal RleId { get; set; }
        public decimal ModId { get; set; }
        public decimal ActId { get; set; }
        public Nullable<bool> MamIsEnable { get; set; }
        public System.DateTime MrmCreatedTs { get; set; }
        public Nullable<System.DateTime> MrmUpdatedTs { get; set; }
        public Nullable<decimal> MrmCreatedBy { get; set; }
        public Nullable<decimal> MrmUpdatedBy { get; set; }
        public string AuditAction { get; set; }
        public System.DateTime AuditDate { get; set; }
        public string AuditUser { get; set; }
        public string AuditApp { get; set; }
    }
}
