//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LG_MODULE_TYPE_AUD
    {
       [Key]
        public long AuditId { get; set; }
        public decimal MteId { get; set; }
        public string MteName { get; set; }
        public string MteCaption { get; set; }
        public System.DateTime MteCreatedTs { get; set; }
        public Nullable<System.DateTime> MteUpdatedTs { get; set; }
        public Nullable<decimal> MteCreatedBy { get; set; }
        public Nullable<decimal> MteUpdatedBy { get; set; }
        public string AuditAction { get; set; }
        public System.DateTime AuditDate { get; set; }
        public string AuditUser { get; set; }
        public string AuditApp { get; set; }
    }
}
