//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LG_MODULE_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LG_MODULE_TYPE()
        {
            this.LG_MODULE = new HashSet<LG_MODULE>();
        }
        [Key]
        public decimal MteId { get; set; }
        public string MteName { get; set; }
        public string MteCaption { get; set; }
        public System.DateTime MteCreatedTs { get; set; }
        public Nullable<System.DateTime> MteUpdatedTs { get; set; }
        public Nullable<decimal> MteCreatedBy { get; set; }
        public Nullable<decimal> MteUpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LG_MODULE> LG_MODULE { get; set; }
    }
}
