//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_QuickBook_MAPP
    {
        public int iID { get; set; }
        public Nullable<int> Contactid { get; set; }
        public Nullable<int> QuickBookID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Createby { get; set; }
        public string ContactStatus { get; set; }
        public string Modifyby { get; set; }
        public Nullable<System.DateTime> Modifyon { get; set; }
        public Nullable<int> QBBillAddID { get; set; }
    }
}
