//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_QB_ENV_CONFIG
    {
        public int iId { get; set; }
        public string Environment { get; set; }
        public string Clientid { get; set; }
        public string ClientScretId { get; set; }
        public string URL { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Creadedon { get; set; }
        public Nullable<int> Creadtedby { get; set; }
        public Nullable<System.DateTime> Modifiedon { get; set; }
        public Nullable<int> Modifyby { get; set; }
        public string BasicAuthCode { get; set; }
    }
}
