//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_QUICKBOOK_MappMessage
    {
        public int QBMsgID { get; set; }
        public Nullable<int> Contactid { get; set; }
        public Nullable<int> QBID { get; set; }
        public string QBDomain { get; set; }
        public string QBStatus { get; set; }
        public string QBResult { get; set; }
        public string QBMessage { get; set; }
        public Nullable<System.DateTime> CreadedOn { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<int> Creadby { get; set; }
    }
}
