//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_QUICKBOOK_MAPPING
    {
        public int LQM_ID { get; set; }
        public string SysRefNo { get; set; }
        public Nullable<int> LQM_QB_ID { get; set; }
        public Nullable<int> LQM_Createdby { get; set; }
        public Nullable<System.DateTime> LQM_Createdon { get; set; }
        public string LQM_STATUS { get; set; }
        public Nullable<int> LQM_Modifyby { get; set; }
        public Nullable<System.DateTime> LQM_Modifyon { get; set; }
        public string LQM_QBID1 { get; set; }
        public Nullable<int> LQM_QBID2 { get; set; }
        public Nullable<int> LQM_QBID3 { get; set; }
        public string LQM_APINAME { get; set; }
    }
}
