//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_QUICKBOOK_ACCESSDETAILS
    {
        public int iId { get; set; }
        public string authCode { get; set; }
        public string accessToken { get; set; }
        public string refreshToken { get; set; }
        public string realmId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
