//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_REFRESH_TOCKENS
    {
        public int iID { get; set; }
        public string Authcode { get; set; }
        public string FirstAccessToken { get; set; }
        public string RefreshToken { get; set; }
        public string RealmID { get; set; }
        public Nullable<System.DateTime> RefTokenCreatedDate { get; set; }
        public Nullable<System.DateTime> RefTokenModifiedDate { get; set; }
        public string AccessToken { get; set; }
        public Nullable<System.DateTime> AccessTokenCreatedDate { get; set; }
        public Nullable<System.DateTime> AccessTokenModifydate { get; set; }
        public string Environment { get; set; }
        public string Status { get; set; }
    }
}
