//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LG_ROLE_AUD
    {
      [Key]
        public long AuditId { get; set; }
        public decimal RleId { get; set; }
        public string RleName { get; set; }
        public Nullable<bool> RleStatus { get; set; }
        public System.DateTime RleCreatedTs { get; set; }
        public Nullable<System.DateTime> RleUpdatedTs { get; set; }
        public bool RleDisplay { get; set; }
        public string rleType { get; set; }
        public Nullable<decimal> RleCreatedBy { get; set; }
        public Nullable<decimal> RleUpdatedBy { get; set; }
        public string AuditAction { get; set; }
        public System.DateTime AuditDate { get; set; }
        public string AuditUser { get; set; }
        public string AuditApp { get; set; }
    }
}
