//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LG_SITE_AUD
    {
        [Key]
        public long AuditId { get; set; }
        public decimal SitId { get; set; }
        public decimal LcnId { get; set; }
        public decimal SitType { get; set; }
        public string SitName { get; set; }
        public string SitCode { get; set; }
        public Nullable<bool> SitStatus { get; set; }
        public string SitReason { get; set; }
        public System.DateTime SitCreatedTs { get; set; }
        public Nullable<System.DateTime> SitUpdatedTs { get; set; }
        public Nullable<decimal> SitCreatedBy { get; set; }
        public Nullable<decimal> SitUpdatedBy { get; set; }
        public string AuditAction { get; set; }
        public System.DateTime AuditDate { get; set; }
        public string AuditUser { get; set; }
        public string AuditApp { get; set; }
    }
}
