//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_SYSTEM_CONFIG
    {
        public decimal SysConfigId { get; set; }
        public string SysConfigName { get; set; }
        public string SysConfigValue { get; set; }
        public Nullable<decimal> SysConfigCreatedBy { get; set; }
        public Nullable<decimal> SysConfigUpdatedBy { get; set; }
        public System.DateTime SysConfigCreatedTs { get; set; }
        public Nullable<System.DateTime> SysConfigUpdatedTs { get; set; }
    }
}
