//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LG_SITE_CONTACT_ROLE_AUD
    {
       [Key]
        public long AuditId { get; set; }
        public decimal ScrId { get; set; }
        public Nullable<decimal> SitId { get; set; }
        public decimal CntId { get; set; }
        public decimal RleId { get; set; }
        public System.DateTime ScrCreatedTs { get; set; }
        public Nullable<System.DateTime> ScrUpdatedTs { get; set; }
        public Nullable<decimal> ScrCreatedBy { get; set; }
        public Nullable<decimal> ScrUpdatedBy { get; set; }
        public string AuditAction { get; set; }
        public System.DateTime AuditDate { get; set; }
        public string AuditUser { get; set; }
        public string AuditApp { get; set; }
    }
}
