//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_TAXCODE
    {
        public int iID { get; set; }
        public string TX_ID { get; set; }
        public string TX_Name { get; set; }
        public string TX_Description { get; set; }
        public string TX_Environment { get; set; }
        public string TX_ISDefault { get; set; }
    }
}
