//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LG_TIMEZONE_AUD
    {
      [Key]
        public long AuditId { get; set; }
        public decimal TmzId { get; set; }
        public string TmzName { get; set; }
        public string TmzOffset { get; set; }
        public string TmzAbbrev { get; set; }
        public string TmzLocation { get; set; }
        public Nullable<bool> TmzStatus { get; set; }
        public System.DateTime TmzCreatedTs { get; set; }
        public Nullable<System.DateTime> TmzUpdatedTs { get; set; }
        public Nullable<decimal> TmzCreatedBy { get; set; }
        public Nullable<decimal> TmzUpdatedBy { get; set; }
        public string AuditAction { get; set; }
        public System.DateTime AuditDate { get; set; }
        public string AuditUser { get; set; }
        public string AuditApp { get; set; }
    }
}
