//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_TRUCKING_CHARGES
    {
        public decimal TrkQuotationID { get; set; }
        public decimal TrkEnquiryID { get; set; }
        public Nullable<decimal> TrkBuyingRate { get; set; }
        public Nullable<decimal> TrkSellingRate { get; set; }
        public Nullable<decimal> TrkContainerID { get; set; }
        public System.DateTime TrkCreatedTs { get; set; }
        public Nullable<System.DateTime> TrkUpdatedTs { get; set; }
        public Nullable<decimal> TrkCreatedBy { get; set; }
        public Nullable<decimal> TrkUpdatedBy { get; set; }
    }
}
