//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LG_USER_AUD
    {
      [Key]
        public long AuditId { get; set; }
        public decimal UsrId { get; set; }
        public decimal CntId { get; set; }
        public string AspNetUserId { get; set; }
        public string UsrPwd { get; set; }
        public string UsrTempPwd { get; set; }
        public System.DateTime UsrPwdCreatedTs { get; set; }
        public Nullable<System.DateTime> UsrValidFrom { get; set; }
        public Nullable<System.DateTime> UsrValidTo { get; set; }
        public Nullable<decimal> UsrFailedCount { get; set; }
        public Nullable<decimal> UsrIsLocked { get; set; }
        public Nullable<decimal> UsrPwdNeverExpire { get; set; }
        public Nullable<System.DateTime> UsrLastLoginTs { get; set; }
        public Nullable<bool> UsrIsPowerUser { get; set; }
        public System.DateTime UsrCreatedTs { get; set; }
        public Nullable<System.DateTime> UsrUpdatedTs { get; set; }
        public Nullable<decimal> UsrCreatedBy { get; set; }
        public Nullable<decimal> UsrUpdatedBy { get; set; }
        public string AuditAction { get; set; }
        public System.DateTime AuditDate { get; set; }
        public string AuditUser { get; set; }
        public string AuditApp { get; set; }
    }
}
