//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LG_USSTATE_AUD
    {
      [Key]
        public long AuditId { get; set; }
        public decimal UstId { get; set; }
        public string UstName { get; set; }
        public string UstAbbrev { get; set; }
        public Nullable<bool> UstStatus { get; set; }
        public System.DateTime UstCreatedTs { get; set; }
        public Nullable<System.DateTime> UstUpdatedTs { get; set; }
        public Nullable<decimal> UstCreatedBy { get; set; }
        public Nullable<decimal> UstUpdatedBy { get; set; }
        public string AuditAction { get; set; }
        public System.DateTime AuditDate { get; set; }
        public string AuditUser { get; set; }
        public string AuditApp { get; set; }
    }
}
