//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LG_VW_DisplayRate
    {
       [Key]
        public int CCID { get; set; }
        public string Commodity { get; set; }
        public string Route { get; set; }
        public string OriginType { get; set; }
        public string DestinationType { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string ViaType1 { get; set; }
        public string ViaType2 { get; set; }
        public string Via1Name { get; set; }
        public string Via2Name { get; set; }
        public Nullable<double> Rate { get; set; }
        public string ContractNo { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public Nullable<decimal> ContractID { get; set; }
        public string Carrier { get; set; }
        public Nullable<int> RouteId { get; set; }
        public Nullable<double> Standard20 { get; set; }
        public Nullable<double> Standard40 { get; set; }
        public Nullable<double> HighCube40 { get; set; }
        public Nullable<double> C45F { get; set; }
        public Nullable<double> SurST20 { get; set; }
        public Nullable<double> SurST40 { get; set; }
        public Nullable<double> SurHC40 { get; set; }
        public Nullable<double> Sur45F { get; set; }
        public string Remarks { get; set; }
        public string ContractRemark { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public string Status { get; set; }

       
    }
}
