//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LG_VW_TradeMaster
    {
       [Key]
        public int Tradeid { get; set; }
        public string TradeLine { get; set; }
        public string TradeCode { get; set; }
        public string Type { get; set; }
        public bool IsActive { get; set; }
        public string CountryId { get; set; }
    }
}
