//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LG_VW_SITE_CONTACT
    {
       [Key]
        public decimal UsrId { get; set; }
        public decimal CntId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> SitId { get; set; }
    }
}
