//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LG_VW_ROUTING
    {
        [Key]
        public int RouteId { get; set; }
        public string Name { get; set; }
        public string OriginType { get; set; }
        public string DestinationType { get; set; }
        public int fkDestinationID { get; set; }
        public int fkOriginID { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public int ViaID { get; set; }
        public string ViaType1 { get; set; }
        public string ViaType2 { get; set; }
        public Nullable<int> Via1 { get; set; }
        public Nullable<int> Via2 { get; set; }
        public string Via1Name { get; set; }
        public string Via2Name { get; set; }
    }
}
