//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class RolewisePermission
    {
       [Key]
        public int RolePermissionID { get; set; }
        public int fkRoleID { get; set; }
        public int fkMenuGenerationID { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Sipl_FormMenuGeneration Sipl_FormMenuGeneration { get; set; }
    }
}
