//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class SIPL_AWB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIPL_AWB()
        {
            this.SIPL_AWBOtherDetail = new HashSet<SIPL_AWBOtherDetail>();
        }
    [Key]
        public int AWBID { get; set; }
        public string FileNo { get; set; }
        public Nullable<int> ShipperID { get; set; }
        public Nullable<int> ConsigneeID { get; set; }
        public string ShipperAccountNumber { get; set; }
        public string ConsigneeAccountNumber { get; set; }
        public Nullable<int> AgentID { get; set; }
        public string AccountingInformation { get; set; }
        public string AgentsIATACode { get; set; }
        public string AccountNo { get; set; }
        public string IssuedBy { get; set; }
        public Nullable<int> AirportOfDeparture { get; set; }
        public string To1 { get; set; }
        public string ByfirstCarrier { get; set; }
        public string RoutingAndDestination { get; set; }
        public string To2 { get; set; }
        public string By1 { get; set; }
        public string To3 { get; set; }
        public string By2 { get; set; }
        public string ReferenceNumber { get; set; }
        public string OptionShippingInformation { get; set; }
        public string Currency { get; set; }
        public string CHGSCOde { get; set; }
        public string PPD1 { get; set; }
        public string COLL1 { get; set; }
        public string PPD2 { get; set; }
        public string COLL2 { get; set; }
        public string DeclaredValueCarriage { get; set; }
        public string DeclaredValueCustom { get; set; }
        public Nullable<int> AirportofDestination { get; set; }
        public string AmountoFinsurance { get; set; }
        public string PrepaidWeightCharge { get; set; }
        public string CollectValuationCharge { get; set; }
        public string CollectWeightCharge { get; set; }
        public string PrepaidValuationCharge { get; set; }
        public string Tax { get; set; }
        public string TotalOtherChargeDueAgent { get; set; }
        public string TotalOtherChargeDueCarrier { get; set; }
        public string TotalPrepaid { get; set; }
        public string TotalCollect { get; set; }
        public string CurrencyConversionFlates { get; set; }
        public string CCCharges { get; set; }
        public string TotalCollectCharge { get; set; }
        public string ForCarriersUuseOnlyAtDestination { get; set; }
        public string ChangesAtDestination { get; set; }
        public string OtherCharge { get; set; }
        public string Place { get; set; }
        public Nullable<System.DateTime> ExecutedOn { get; set; }
        public string RequestedFlight { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public int CommonID { get; set; }
        public Nullable<int> UpdateID { get; set; }
        public string CollectTax { get; set; }
        public string CollectTotalOtherChargeDueAgent { get; set; }
        public string CollectTotalOtherChargeDueCarrier { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_AWBOtherDetail> SIPL_AWBOtherDetail { get; set; }
    }
}
