//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_FreightCharges
    {
        public int FreightChargesID { get; set; }
        public int CommonID { get; set; }
        public string FREIGHTCharge { get; set; }
        public string PREPAID { get; set; }
        public string COLLECT { get; set; }
        public string Type { get; set; }
    }
}
