//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_MarketingMail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIPL_MarketingMail()
        {
            this.SIPL_FollowUpDateEntry = new HashSet<SIPL_FollowUpDateEntry>();
            this.SIPL_FollowUpDateEntry1 = new HashSet<SIPL_FollowUpDateEntry>();
        }
    
        public int ID { get; set; }
        public int fkUserId { get; set; }
        public int fkCompanyId { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public string Remarks { get; set; }
        public bool IsReminder { get; set; }
        public string Body { get; set; }
        public string Subject { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
        public string ToEmailId { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual SIPL_Contact SIPL_Contact { get; set; }
        public virtual SIPL_Contact SIPL_Contact1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_FollowUpDateEntry> SIPL_FollowUpDateEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_FollowUpDateEntry> SIPL_FollowUpDateEntry1 { get; set; }
        public virtual SIPL_User SIPL_User { get; set; }
        public virtual SIPL_User SIPL_User1 { get; set; }
    }
}
