//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_Company
    {
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string TelNo { get; set; }
        public string Address { get; set; }
        public string Fax { get; set; }
        public Nullable<int> fkStateID { get; set; }
        public string CityName { get; set; }
        public string ContactPerson { get; set; }
        public string Email { get; set; }
        public string ZipCode { get; set; }
        public string Remarks { get; set; }
    
        public virtual SIPL_State SIPL_State { get; set; }
    }
}
