//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_HouseBLDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIPL_HouseBLDetail()
        {
            this.SIPL_HoBLSubDetail = new HashSet<SIPL_HoBLSubDetail>();
        }
    
        public int HouseBLID { get; set; }
        public string CommonID { get; set; }
        public string FileNo { get; set; }
        public Nullable<int> ExporterID { get; set; }
        public string BillLaddingNumber { get; set; }
        public string ExportRef { get; set; }
        public Nullable<int> ConsignedTo { get; set; }
        public Nullable<int> FwdAgent { get; set; }
        public Nullable<int> ConsigneeID { get; set; }
        public string ExportInstruction { get; set; }
        public string CarriageBy { get; set; }
        public string PlaceOfReceiptID { get; set; }
        public string LandingPortID { get; set; }
        public string DeschargePortID { get; set; }
        public string LoadingPert { get; set; }
        public string MoveType { get; set; }
        public string Transshipment { get; set; }
        public string Vessel { get; set; }
        public string BookingNo { get; set; }
        public string Place { get; set; }
        public Nullable<int> YearID { get; set; }
        public Nullable<int> MonthID { get; set; }
        public Nullable<int> DayID { get; set; }
        public string ReceivedBy { get; set; }
        public string AgentAddr { get; set; }
        public string DECLAREDValue { get; set; }
        public string SEECLAUSE { get; set; }
        public string Type { get; set; }
        public string BillNumber { get; set; }
        public string PlaceOfAcceptance { get; set; }
        public string DocNumber { get; set; }
        public string Voyage { get; set; }
        public string FTZNumber { get; set; }
        public string ExportingCarrier { get; set; }
        public Nullable<int> ContainerizedID { get; set; }
        public string ReadClause { get; set; }
        public Nullable<System.DateTime> DateAT { get; set; }
        public Nullable<int> UpdateID { get; set; }
        public string deliveryCarrierID { get; set; }
        public string ConsignedToType { get; set; }
        public Nullable<int> IsPrintAddress { get; set; }
        public string RefAdd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_HoBLSubDetail> SIPL_HoBLSubDetail { get; set; }
    }
}
