//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_ContractApplicableCharges
    {
        public int ApplicableID { get; set; }
        public Nullable<int> fkContractID { get; set; }
        public Nullable<int> fkChargesID { get; set; }
        public Nullable<System.DateTime> EffectFrom { get; set; }
        public Nullable<System.DateTime> ExpireOn { get; set; }
    
        public virtual SIPL_Charges SIPL_Charges { get; set; }
        public virtual SIPL_ContractShipline SIPL_ContractShipline { get; set; }
    }
}
