//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_EnquiryServiceRequiredFCL
    {
        public int FCLID { get; set; }
        public int fkServiceRequiredID { get; set; }
        public Nullable<int> NoofContainer { get; set; }
        public int fkContainerTypeID { get; set; }
        public decimal fkEnquiryID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual SIPL_ContainerSize SIPL_ContainerSize { get; set; }
        public virtual SIPL_Enquiry SIPL_Enquiry { get; set; }
        public virtual SIPL_LoadType SIPL_LoadType { get; set; }
    }
}
