//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_ChargesCategoryMapping
    {
        public int ChargesCategoryMappingId { get; set; }
        public Nullable<int> fkChargesCategoryId { get; set; }
        public Nullable<int> fkChargesId { get; set; }
    
        public virtual SIPL_Charges SIPL_Charges { get; set; }
        public virtual SIPL_ChargesCategory SIPL_ChargesCategory { get; set; }
    }
}
