//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_SLTSConfigurator
    {
        public int SLTSConfiguratorId { get; set; }
        public Nullable<int> fkShipLineId { get; set; }
        public Nullable<int> fkTradeServiceId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual SIPL_Contact SIPL_Contact { get; set; }
        public virtual SIPL_TradeService SIPL_TradeService { get; set; }
    }
}
