//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_AWBOtherDetail
    {
        public int AWBOtherDetailID { get; set; }
        public int AWBID { get; set; }
        public string Noofpieces { get; set; }
        public string Grossweight { get; set; }
        public string Rateclass { get; set; }
        public string Chargeable { get; set; }
        public string charge { get; set; }
        public string Total { get; set; }
        public string NatureAndQuantity { get; set; }
    
        public virtual SIPL_AWB SIPL_AWB { get; set; }
    }
}
