//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_PickupLoading
    {
        public decimal PickupID { get; set; }
        public int CommonID { get; set; }
        public string FileNo { get; set; }
        public string ExportRefNo { get; set; }
        public string LoadingLocation { get; set; }
        public string LLAttn { get; set; }
        public string LLAddress { get; set; }
        public string LLTelNo { get; set; }
        public string LLFaxNo { get; set; }
        public string PURContactPerson { get; set; }
        public string PURAtten { get; set; }
        public string PURAddress { get; set; }
        public string PURTelno { get; set; }
        public string PURFaxNo { get; set; }
        public string PDRName { get; set; }
        public string PDRAttn { get; set; }
        public string PDRAddress { get; set; }
        public string PDRTelNo { get; set; }
        public string PUDFaxNo { get; set; }
        public Nullable<System.DateTime> PURPickupDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string LLCarrier { get; set; }
        public string SIBLNo { get; set; }
        public string SIVoyage { get; set; }
        public string SIVessel { get; set; }
        public Nullable<int> SIConsigneeID { get; set; }
        public string SIDest { get; set; }
        public Nullable<int> Package { get; set; }
        public string Commodity { get; set; }
        public string Weight { get; set; }
        public string PURName { get; set; }
        public string Dims { get; set; }
        public string Number { get; set; }
        public string Booking { get; set; }
        public Nullable<System.DateTime> CutOFF { get; set; }
        public string SIEmptyPickup { get; set; }
        public string SIEmptyPickupID { get; set; }
        public string SIReceivedAt { get; set; }
        public string SITime { get; set; }
        public Nullable<System.DateTime> SIDate { get; set; }
        public string PURInstruction { get; set; }
        public Nullable<System.DateTime> PDRDeliverydate { get; set; }
        public string PDRInstruction { get; set; }
        public string ECPULLocation { get; set; }
        public string ECPULTelNo { get; set; }
        public string ECPULContactPerson { get; set; }
        public string ECPULInstruction { get; set; }
        public Nullable<System.DateTime> FCRCutoffdate { get; set; }
        public string FCRLocation { get; set; }
        public string FCRTelNo { get; set; }
        public string FCRAttn { get; set; }
        public string FCRInstruction { get; set; }
        public string AutAttn { get; set; }
        public string AutLocation { get; set; }
        public string AutTelNo { get; set; }
        public string FreightCharges { get; set; }
        public string SpecialInstruction { get; set; }
        public string AutFaxNo { get; set; }
        public string LLSI { get; set; }
        public string SIConsigneeAdd { get; set; }
        public string SIConsigneeFullAdd { get; set; }
    }
}
