//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_ContractSurcharge
    {
        public decimal ContractSurchargeID { get; set; }
        public Nullable<decimal> fkContractCarrierID { get; set; }
        public int SurchargeID { get; set; }
        public double Rate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
    
        public virtual SIPL_ContractCarrier SIPL_ContractCarrier { get; set; }
        public virtual SIPL_TradeService SIPL_TradeService { get; set; }
    }
}
