//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_EnquiryServiceRequired
    {
        public decimal EnquiryServiceRequiredId { get; set; }
        public Nullable<decimal> fkEnquiryId { get; set; }
        public Nullable<int> fkLoadTypeId { get; set; }
        public Nullable<int> PieceCount { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> TotalWeight { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Volume { get; set; }
        public string Description { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> Inland { get; set; }
        public string InlandRemarks { get; set; }
        public Nullable<double> MafiCharges { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual SIPL_Enquiry SIPL_Enquiry { get; set; }
        public virtual SIPL_LoadType SIPL_LoadType { get; set; }
    }
}
