//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sipl_FormMenuGeneration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sipl_FormMenuGeneration()
        {
            this.RolewisePermissions = new HashSet<RolewisePermission>();
            this.SIPL_FormOperationPermission = new HashSet<SIPL_FormOperationPermission>();
        }
    
        public int MenuGenerationID { get; set; }
        public string FormName { get; set; }
        public string FirstModule { get; set; }
        public Nullable<int> FirstModuleOrder { get; set; }
        public string SecondModule { get; set; }
        public Nullable<int> SecondModuleOrder { get; set; }
        public string ThirdModule { get; set; }
        public Nullable<int> ThridModuleOrder { get; set; }
        public string FormPath { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolewisePermission> RolewisePermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_FormOperationPermission> SIPL_FormOperationPermission { get; set; }
    }
}
