//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_DispatchTable
    {
        public int ID { get; set; }
        public Nullable<int> CommonID { get; set; }
        public Nullable<int> ServiceRefID { get; set; }
        public Nullable<int> fkContainerTypeID { get; set; }
        public string SealNo { get; set; }
        public string CNTNo { get; set; }
        public string Remark { get; set; }
        public Nullable<int> SeqNo { get; set; }
    }
}
