//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_ContractPort
    {
        public decimal ContractPortID { get; set; }
        public decimal fkContractID { get; set; }
        public int fkOriginID { get; set; }
        public int fkDestinationID { get; set; }
    
        public virtual SIPL_Port SIPL_Port { get; set; }
        public virtual SIPL_Port SIPL_Port1 { get; set; }
        public virtual SIPL_Port SIPL_Port2 { get; set; }
    }
}
