//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_ShippingLineRate
    {
        public decimal ShippingLineRateId { get; set; }
        public Nullable<int> fkShilpLineId { get; set; }
        public Nullable<int> fkSourceId { get; set; }
        public Nullable<int> fkDetinationId { get; set; }
        public Nullable<int> fkToModeId { get; set; }
        public Nullable<int> fkFromModeId { get; set; }
        public Nullable<int> fkContainberSizeId { get; set; }
        public Nullable<double> Rates { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> Flag { get; set; }
    
        public virtual SIPL_City SIPL_City { get; set; }
        public virtual SIPL_City SIPL_City1 { get; set; }
        public virtual SIPL_ContainerSize SIPL_ContainerSize { get; set; }
        public virtual SIPL_Mode SIPL_Mode { get; set; }
        public virtual SIPL_Mode SIPL_Mode1 { get; set; }
        public virtual SIPL_ShippingLine SIPL_ShippingLine { get; set; }
    }
}
