//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class SIPL_AirCargo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIPL_AirCargo()
        {
            this.AirCargoSubDetails = new HashSet<AirCargoSubDetail>();
        }
    [Key]
        public int AirCargoID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> AirlineID { get; set; }
        public Nullable<int> OriginAirportID { get; set; }
        public string Mawb { get; set; }
        public Nullable<int> FlightsID { get; set; }
        public Nullable<int> DestinationAirportID { get; set; }
        public string FileNo { get; set; }
        public int CommonID { get; set; }
        public Nullable<int> UpdateID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AirCargoSubDetail> AirCargoSubDetails { get; set; }
    }
}
