//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class SIPL_BasicRateDueDate
    {
       [Key]
        public decimal BRDDID { get; set; }
        public decimal fkContractID { get; set; }
        public decimal RefID { get; set; }
        public string Ref { get; set; }
        public double Rate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int CommodityId { get; set; }
        public int RouteId { get; set; }
    }
}
