//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_ContainerSize
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIPL_ContainerSize()
        {
            this.SIPL_EnquiryContainerType = new HashSet<SIPL_EnquiryContainerType>();
            this.SIPL_EnquiryServiceRequiredFCL = new HashSet<SIPL_EnquiryServiceRequiredFCL>();
            this.SIPL_ShippingLineRate = new HashSet<SIPL_ShippingLineRate>();
        }
    
        public int ContainerSizeId { get; set; }
        public int fkContainerTypeID { get; set; }
        public string ContainerSize { get; set; }
        public Nullable<double> CapacityInTons { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> Flag { get; set; }
    
        public virtual SIPL_ContainerType SIPL_ContainerType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_EnquiryContainerType> SIPL_EnquiryContainerType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_EnquiryServiceRequiredFCL> SIPL_EnquiryServiceRequiredFCL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_ShippingLineRate> SIPL_ShippingLineRate { get; set; }
    }
}
