//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_CurrencySymbol
    {
        public int CurrencyID { get; set; }
        public string Currency { get; set; }
        public string CurrencyCode { get; set; }
        public string Symbol { get; set; }
        public int CountryID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
