//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_DocumentCommonOD
    {
        public int DCOtherID { get; set; }
        public int DCID { get; set; }
        public string Number { get; set; }
        public string Package { get; set; }
        public string Commodity { get; set; }
        public string Weight { get; set; }
        public string Measuremant { get; set; }
        public string Type { get; set; }
        public string WtType { get; set; }
        public string MtType { get; set; }
    
        public virtual SIPL_DocumentCommon SIPL_DocumentCommon { get; set; }
    }
}
