//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_DataAccessPermission
    {
        public int DataAccessPermissionId { get; set; }
        public Nullable<int> fkUserId { get; set; }
        public Nullable<int> fkCountryId { get; set; }
        public Nullable<bool> IsView { get; set; }
    
        public virtual SIPL_Country SIPL_Country { get; set; }
        public virtual SIPL_User SIPL_User { get; set; }
    }
}
