//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_Enquiry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIPL_Enquiry()
        {
            this.SIPL_EnquiryServiceRequired = new HashSet<SIPL_EnquiryServiceRequired>();
            this.SIPL_EnquiryCommodity = new HashSet<SIPL_EnquiryCommodity>();
            this.SIPL_EnquiryServiceRequiredFCL = new HashSet<SIPL_EnquiryServiceRequiredFCL>();
            this.SIPL_EnquiryServiceRequiredRORO = new HashSet<SIPL_EnquiryServiceRequiredRORO>();
            this.SIPL_Quotation = new HashSet<SIPL_Quotation>();
        }
    
        public decimal EnquiryID { get; set; }
        public Nullable<System.DateTime> EnquiryDate { get; set; }
        public string EnquiryNo { get; set; }
        public Nullable<int> fkCompanyID { get; set; }
        public Nullable<System.DateTime> ShipmentMoveDate { get; set; }
        public string PickupType { get; set; }
        public string PickupRemark { get; set; }
        public int PortOfOrigin { get; set; }
        public int PortOfDischarge { get; set; }
        public Nullable<int> NoOfContainer { get; set; }
        public Nullable<int> TypeOfEnquiry { get; set; }
        public Nullable<int> ReceivedBy { get; set; }
        public string Remarks { get; set; }
        public string Description { get; set; }
        public Nullable<double> Class { get; set; }
        public string UNNo { get; set; }
        public string PackingType { get; set; }
        public string HazRemarks { get; set; }
        public Nullable<bool> IsHaz { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<double> Hazweight { get; set; }
        public Nullable<double> HazVolume { get; set; }
        public Nullable<int> OriginCountryID { get; set; }
        public Nullable<int> DestinationCountryID { get; set; }
        public Nullable<int> OrignStateID { get; set; }
        public Nullable<int> DestinationStateID { get; set; }
        public Nullable<int> OriginCityID { get; set; }
        public Nullable<int> DestinationCityID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> IsDraft { get; set; }
        public string CustomerInqNo { get; set; }
        public string DestinationDoor { get; set; }
        public string OriginDoor { get; set; }
        public Nullable<int> GalRepID { get; set; }
        public Nullable<int> OrgnRailRampId { get; set; }
        public Nullable<int> DestnTerminalId { get; set; }
        public string DelRemarks { get; set; }
        public decimal SitId { get; set; }
        public Nullable<decimal> UpdatedBy { get; set; }
        public Nullable<int> BillTo { get; set; }
        public Nullable<int> BillToCompanyId { get; set; }
        public Nullable<int> LicenseType { get; set; }
    
        public virtual LG_SITE LG_SITE { get; set; }
        public virtual SIPL_City SIPL_City { get; set; }
        public virtual SIPL_City SIPL_City1 { get; set; }
        public virtual SIPL_Contact SIPL_Contact { get; set; }
        public virtual SIPL_Country SIPL_Country { get; set; }
        public virtual SIPL_Country SIPL_Country1 { get; set; }
        public virtual SIPL_Department SIPL_Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_EnquiryServiceRequired> SIPL_EnquiryServiceRequired { get; set; }
        public virtual SIPL_Port SIPL_Port { get; set; }
        public virtual SIPL_Port SIPL_Port1 { get; set; }
        public virtual SIPL_State SIPL_State { get; set; }
        public virtual SIPL_State SIPL_State1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_EnquiryCommodity> SIPL_EnquiryCommodity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_EnquiryServiceRequiredFCL> SIPL_EnquiryServiceRequiredFCL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_EnquiryServiceRequiredRORO> SIPL_EnquiryServiceRequiredRORO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_Quotation> SIPL_Quotation { get; set; }
    }
}
