//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_QuotationRemarks
    {
        public decimal QuotationRemarksID { get; set; }
        public Nullable<decimal> RefID { get; set; }
        public string Ref { get; set; }
        public Nullable<int> fkCarrierID { get; set; }
        public decimal fkQuotationID { get; set; }
        public string Remarks { get; set; }
        public bool IsApplicable { get; set; }
    
        public virtual SIPL_Contact SIPL_Contact { get; set; }
        public virtual SIPL_Quotation SIPL_Quotation { get; set; }
    }
}
