//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class SIPL_ArivalOD
    {
       [Key]
        public int ArivalODID { get; set; }
        public int ArivalID { get; set; }
        public string Charges { get; set; }
        public string Basis { get; set; }
        public string Rate { get; set; }
        public string Amount { get; set; }
    
        public virtual SIPL_ArivalNotice SIPL_ArivalNotice { get; set; }
    }
}
