//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_Quotation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIPL_Quotation()
        {
            this.SIPL_GenerateEmail = new HashSet<SIPL_GenerateEmail>();
            this.SIPL_QuotationCarrier = new HashSet<SIPL_QuotationCarrier>();
            this.SIPL_QuotationCharges = new HashSet<SIPL_QuotationCharges>();
            this.SIPL_QuotationCommodity = new HashSet<SIPL_QuotationCommodity>();
            this.SIPL_QuotationPayableCharges = new HashSet<SIPL_QuotationPayableCharges>();
            this.SIPL_QuotationPayableRemarks = new HashSet<SIPL_QuotationPayableRemarks>();
            this.SIPL_QuotationRemarks = new HashSet<SIPL_QuotationRemarks>();
        }
    
        public decimal QuotationID { get; set; }
        public decimal fkEnquiryID { get; set; }
        public string PaymentTerms { get; set; }
        public string OtherTerms { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string QuotationNo { get; set; }
        public int fkAgentID { get; set; }
        public Nullable<int> Originportid { get; set; }
        public Nullable<int> Destinitionportid { get; set; }
        public int fkContactID { get; set; }
        public System.DateTime EffectFromDate { get; set; }
        public int IsApproved { get; set; }
        public double TruckingCharges { get; set; }
        public Nullable<int> IsDraft { get; set; }
        public string TruckingRemarks { get; set; }
        public Nullable<bool> IsBooked { get; set; }
        public Nullable<System.DateTime> ValidTill { get; set; }
        public string CarriageCurrency { get; set; }
        public Nullable<double> BuyingTruckingCharge { get; set; }
        public string DelRemarks { get; set; }
        public Nullable<System.DateTime> CustReqCutOffDate { get; set; }
        public Nullable<System.DateTime> CustReqSailingDate { get; set; }
        public Nullable<System.DateTime> BookingReqtRecivedDate { get; set; }
    
        public virtual SIPL_Enquiry SIPL_Enquiry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_GenerateEmail> SIPL_GenerateEmail { get; set; }
        public virtual SIPL_Port SIPL_Port { get; set; }
        public virtual SIPL_Port SIPL_Port1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_QuotationCarrier> SIPL_QuotationCarrier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_QuotationCharges> SIPL_QuotationCharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_QuotationCommodity> SIPL_QuotationCommodity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_QuotationPayableCharges> SIPL_QuotationPayableCharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_QuotationPayableRemarks> SIPL_QuotationPayableRemarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_QuotationRemarks> SIPL_QuotationRemarks { get; set; }
    }
}
