//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_PayableCharges
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIPL_PayableCharges()
        {
            this.SIPL_QuotationPayableCharges = new HashSet<SIPL_QuotationPayableCharges>();
            this.SIPL_QuotationPayableRemarks = new HashSet<SIPL_QuotationPayableRemarks>();
        }
    
        public int ChargesID { get; set; }
        public string PayableCharges { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual SIPL_User SIPL_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_QuotationPayableCharges> SIPL_QuotationPayableCharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_QuotationPayableRemarks> SIPL_QuotationPayableRemarks { get; set; }
    }
}
