//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class SIPL_BillofLadingOD
    {
       [Key]
        public int DetailID { get; set; }
        public int BillID { get; set; }
        public string Pcs { get; set; }
        public string Description { get; set; }
        public string Weight { get; set; }
        public string Dims { get; set; }
        public string Marks { get; set; }
    
        public virtual SIPL_BillofLading SIPL_BillofLading { get; set; }
    }
}
