//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_Charges
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIPL_Charges()
        {
            this.SIPL_ChargesCategoryMapping = new HashSet<SIPL_ChargesCategoryMapping>();
            this.SIPL_ContractApplicableCharges = new HashSet<SIPL_ContractApplicableCharges>();
            this.SIPL_ContractNonApplicable = new HashSet<SIPL_ContractNonApplicable>();
            this.SIPL_SLChargesConfigurator = new HashSet<SIPL_SLChargesConfigurator>();
            this.SIPL_StandardChargesRate = new HashSet<SIPL_StandardChargesRate>();
            this.SIPL_TSChargesConfigurator = new HashSet<SIPL_TSChargesConfigurator>();
        }
    
        public int ChargesId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> fkChargesCategoryId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> Flag { get; set; }
    
        public virtual SIPL_ChargesCategory SIPL_ChargesCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_ChargesCategoryMapping> SIPL_ChargesCategoryMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_ContractApplicableCharges> SIPL_ContractApplicableCharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_ContractNonApplicable> SIPL_ContractNonApplicable { get; set; }
        public virtual SIPL_ShipLineTSSurCharges SIPL_ShipLineTSSurCharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_SLChargesConfigurator> SIPL_SLChargesConfigurator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_StandardChargesRate> SIPL_StandardChargesRate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_TSChargesConfigurator> SIPL_TSChargesConfigurator { get; set; }
    }
}
