//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class SIPL_ArrivalNoticeFreightOD
    {
       [Key]
        public decimal ArrivalNoticeFreightOID { get; set; }
        public decimal ArrivalNoticeFreightID { get; set; }
        public string Pkgs { get; set; }
        public string Marking { get; set; }
        public string ContainerNo { get; set; }
        public string Description { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Volume { get; set; }
    }
}
