//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_QuotationPayableRemarks
    {
        public decimal QuotationPayRemarksID { get; set; }
        public int fkChargesID { get; set; }
        public decimal fkQuotationID { get; set; }
        public string Remarks { get; set; }
        public bool IsApplicable { get; set; }
        public bool Direction { get; set; }
    
        public virtual SIPL_PayableCharges SIPL_PayableCharges { get; set; }
        public virtual SIPL_Quotation SIPL_Quotation { get; set; }
    }
}
