//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_ExpenseDetail
    {
        public int ExpID { get; set; }
        public string VendorName { get; set; }
        public string DocNo { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string Amount { get; set; }
        public string ExpenseHead { get; set; }
        public string Narration { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> COID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ExpenseHeadID { get; set; }
        public Nullable<decimal> BuyingAmount { get; set; }
        public Nullable<decimal> SellingAmount { get; set; }
    }
}
