//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_ServiceRefernce
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIPL_ServiceRefernce()
        {
            this.SIPL_ServiceRefAll = new HashSet<SIPL_ServiceRefAll>();
            this.SIPL_ServiceRefFCL = new HashSet<SIPL_ServiceRefFCL>();
        }
    
        public decimal ServiceRefID { get; set; }
        public int fkServiceRequiredID { get; set; }
        public int RefID { get; set; }
        public string RefType { get; set; }
        public int IsDeleted { get; set; }
    
        public virtual SIPL_LoadType SIPL_LoadType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_ServiceRefAll> SIPL_ServiceRefAll { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_ServiceRefFCL> SIPL_ServiceRefFCL { get; set; }
    }
}
