//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class SIPL_ArivalNotice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIPL_ArivalNotice()
        {
            this.SIPL_ArivalOD = new HashSet<SIPL_ArivalOD>();
        }
    [Key]
        public int ArivalNoticeID { get; set; }
        public string FileNo { get; set; }
        public Nullable<int> ShipperID { get; set; }
        public string InvoiceNo { get; set; }
        public string LadingNo { get; set; }
        public string RefNo { get; set; }
        public string ApplyTo { get; set; }
        public Nullable<int> ConsigneeID { get; set; }
        public string Notify { get; set; }
        public string Freight { get; set; }
        public string MasterBLNo { get; set; }
        public string Carrier { get; set; }
        public string Departure { get; set; }
        public string EDT { get; set; }
        public Nullable<System.DateTime> DateAvia { get; set; }
        public string FreetTime { get; set; }
        public string CalDays { get; set; }
        public Nullable<int> DischargePlaceID { get; set; }
        public Nullable<int> DeliveryPlaceID { get; set; }
        public string DelETA { get; set; }
        public string DesETA { get; set; }
        public string ITInfo { get; set; }
        public string ITNo { get; set; }
        public Nullable<System.DateTime> ITDate { get; set; }
        public Nullable<int> ITPortID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> BrokerID { get; set; }
        public int CommonID { get; set; }
        public Nullable<int> UpDateID { get; set; }
        public string Comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_ArivalOD> SIPL_ArivalOD { get; set; }
    }
}
