//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_ContactPersonCategoty
    {
        public decimal ContectPersonCateGoryID { get; set; }
        public int ContactID { get; set; }
        public int ContactCategoryID { get; set; }
    
        public virtual SIPL_Contact SIPL_Contact { get; set; }
        public virtual SIPL_ContactCategory SIPL_ContactCategory { get; set; }
    }
}
