//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_BillofLading
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIPL_BillofLading()
        {
            this.SIPL_BillofLadingOD = new HashSet<SIPL_BillofLadingOD>();
        }
    
        public int StraightID { get; set; }
        public string FileNo { get; set; }
        public string Authorized { get; set; }
        public string ATTN { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string PickupAt { get; set; }
        public string PickupATTN { get; set; }
        public string PickUpTel { get; set; }
        public string PickupFax { get; set; }
        public string DeliveryTo { get; set; }
        public string DelATTN { get; set; }
        public string DelTel { get; set; }
        public string DelFax { get; set; }
        public Nullable<System.DateTime> StraightDate { get; set; }
        public Nullable<System.DateTime> PickupDate { get; set; }
        public string Reference { get; set; }
        public string BillCharges { get; set; }
        public string BLNumber { get; set; }
        public string Vessel { get; set; }
        public Nullable<int> Consignee { get; set; }
        public Nullable<int> Destination { get; set; }
        public string BookingLine { get; set; }
        public Nullable<System.DateTime> CutOff { get; set; }
        public string EmptyPU { get; set; }
        public string ID { get; set; }
        public string Received { get; set; }
        public string Time { get; set; }
        public Nullable<System.DateTime> InsDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CommonID { get; set; }
        public Nullable<int> UpdateID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_BillofLadingOD> SIPL_BillofLadingOD { get; set; }
    }
}
