//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_Via
    {
        public int ViaID { get; set; }
        public int RouteId { get; set; }
        public int Via { get; set; }
        public string Type { get; set; }
        public string Sequence { get; set; }
    
        public virtual SIPL_Routing SIPL_Routing { get; set; }
    }
}
