//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sipl_FormMenuGenerationold
    {
        public int MenuGenerationID { get; set; }
        public string FormName { get; set; }
        public string FirstModule { get; set; }
        public Nullable<int> FirstModuleOrder { get; set; }
        public string SecondModule { get; set; }
        public Nullable<int> SecondModuleOrder { get; set; }
        public string ThirdModule { get; set; }
        public Nullable<int> ThridModuleOrder { get; set; }
        public string FormPath { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    }
}
