//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_GenerateEmail
    {
        public decimal GenerationID { get; set; }
        public decimal fkQuotationID { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> MailSend { get; set; }
        public Nullable<System.DateTime> QuotationSentDate { get; set; }
    
        public virtual SIPL_Quotation SIPL_Quotation { get; set; }
    }
}
