//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_ServiceRefFCL
    {
        public decimal ServiceRefFCL { get; set; }
        public decimal ServiceRefID { get; set; }
        public int NoofContainer { get; set; }
        public int fkContainerTypeID { get; set; }
    
        public virtual SIPL_ServiceRefernce SIPL_ServiceRefernce { get; set; }
    }
}
