//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_ShippingLineText
    {
        public int Id { get; set; }
        public string ShipperRemarks { get; set; }
        public string ShipperCommonRemarks { get; set; }
        public string ShipperId { get; set; }
    }
}
