//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_TableField
    {
        public int FieldID { get; set; }
        public int fkDocumentCategoryID { get; set; }
        public string FieldName { get; set; }
    
        public virtual SIPL_DocumentCategory SIPL_DocumentCategory { get; set; }
    }
}
