//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_DocumentCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIPL_DocumentCategory()
        {
            this.SIPL_CategoryTable = new HashSet<SIPL_CategoryTable>();
            this.SIPl_Document_CategoryDocument = new HashSet<SIPl_Document_CategoryDocument>();
            this.SIPL_TableField = new HashSet<SIPL_TableField>();
        }
    
        public int DocumentCategoryID { get; set; }
        public string CategoryName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> IsExport { get; set; }
        public Nullable<int> IsAir { get; set; }
        public Nullable<int> IsImport { get; set; }
        public Nullable<int> IsOcean { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_CategoryTable> SIPL_CategoryTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPl_Document_CategoryDocument> SIPl_Document_CategoryDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_TableField> SIPL_TableField { get; set; }
    }
}
