//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_ContractOriginDestination
    {
        public int ID { get; set; }
        public int fkContractID { get; set; }
        public Nullable<int> fkCountryID { get; set; }
        public string Source { get; set; }
    
        public virtual SIPL_Country SIPL_Country { get; set; }
    }
}
