//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_QuotationPayableCharges
    {
        public decimal PayableChargesID { get; set; }
        public decimal fkQuotationID { get; set; }
        public int fkcontainerID { get; set; }
        public int ChargesID { get; set; }
        public Nullable<double> BuyingCost { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<bool> Isapplicable { get; set; }
        public Nullable<bool> Direction { get; set; }
    
        public virtual SIPL_ContainerType SIPL_ContainerType { get; set; }
        public virtual SIPL_PayableCharges SIPL_PayableCharges { get; set; }
        public virtual SIPL_Quotation SIPL_Quotation { get; set; }
    }
}
