//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_QuotationContainerRate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIPL_QuotationContainerRate()
        {
            this.SIPL_QuotationSurcharesRate = new HashSet<SIPL_QuotationSurcharesRate>();
        }
    
        public decimal QuotationContainerRateID { get; set; }
        public decimal fkQuotationCarrierID { get; set; }
        public int fkContainerID { get; set; }
        public double BuyingRate { get; set; }
        public double SellingRate { get; set; }
        public Nullable<bool> Isapplicable { get; set; }
        public Nullable<bool> IsChecked { get; set; }
    
        public virtual SIPL_QuotationCarrier SIPL_QuotationCarrier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_QuotationSurcharesRate> SIPL_QuotationSurcharesRate { get; set; }
    }
}
