//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_OceanCargo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIPL_OceanCargo()
        {
            this.SIPL_OceanOD = new HashSet<SIPL_OceanOD>();
        }
    
        public int OceanCargoID { get; set; }
        public string FileNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> LineID { get; set; }
        public Nullable<int> PortofLoadingID { get; set; }
        public string MBL { get; set; }
        public string Vessel { get; set; }
        public Nullable<int> PortofUnloading { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public int CommonID { get; set; }
        public Nullable<int> UpdateID { get; set; }
        public string shipperID { get; set; }
        public string ConsigneeID { get; set; }
        public string ERefNo { get; set; }
        public Nullable<int> Isupdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_OceanOD> SIPL_OceanOD { get; set; }
    }
}
