//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_QuotationCommodity
    {
        public int QuotationCommodityID { get; set; }
        public int fkCommodityID { get; set; }
        public decimal fkQuotationID { get; set; }
    
        public virtual SIPL_Commodity SIPL_Commodity { get; set; }
        public virtual SIPL_Quotation SIPL_Quotation { get; set; }
    }
}
