//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_ContractContainer
    {
        public int ContainerID { get; set; }
        public Nullable<int> fkContractID { get; set; }
        public Nullable<int> D20DR { get; set; }
        public Nullable<int> D40DR { get; set; }
        public Nullable<int> D40HD { get; set; }
        public Nullable<int> D20OP { get; set; }
        public Nullable<int> D45DR { get; set; }
        public Nullable<int> D45HD { get; set; }
        public Nullable<int> D1 { get; set; }
        public Nullable<int> D2 { get; set; }
        public string Mode { get; set; }
        public string Route { get; set; }
        public string Type { get; set; }
        public string Remarks { get; set; }
    
        public virtual SIPL_ContractShipline SIPL_ContractShipline { get; set; }
    }
}
