//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_FormPermission
    {
        public int FormPermissionId { get; set; }
        public Nullable<int> fkRoleId { get; set; }
        public Nullable<int> fkMenuGenerationID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual SIPL_Role SIPL_Role { get; set; }
    }
}
