//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_SLCommodityConfigurator
    {
        public int SLCommodityConfiguratorId { get; set; }
        public Nullable<int> fkShipLineId { get; set; }
        public Nullable<int> fkCommodityId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual SIPL_Commodity SIPL_Commodity { get; set; }
        public virtual SIPL_Contact SIPL_Contact { get; set; }
    }
}
