//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_CertificationOfOrigin
    {
        public int COID { get; set; }
        public string FileNo { get; set; }
        public string CommonID { get; set; }
        public Nullable<int> ExporterID { get; set; }
        public string DocumentNumber { get; set; }
        public string BLNumber { get; set; }
        public string Model { get; set; }
        public string FTZNumber { get; set; }
        public string ExportRef { get; set; }
        public Nullable<int> ConsignedTo { get; set; }
        public Nullable<int> FwdAgent { get; set; }
        public Nullable<int> ConsigneeID { get; set; }
        public string ExportInstruction { get; set; }
        public string CarriageBy { get; set; }
        public string PlaceOfReceiptID { get; set; }
        public string ExportingCarrier { get; set; }
        public string LandingPortID { get; set; }
        public string LoadingPert { get; set; }
        public string ForeignPortID { get; set; }
        public string Transshipment { get; set; }
        public string MoveType { get; set; }
        public Nullable<int> Containerized { get; set; }
        public string Undersigned { get; set; }
        public string Date { get; set; }
        public string Dayof1 { get; set; }
        public string Dayof2 { get; set; }
        public string Date2 { get; set; }
        public string DatedAt { get; set; }
        public string Chamber { get; set; }
        public string Stateof { get; set; }
        public string Secretary { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> UpdateID { get; set; }
        public string ConsignedToType { get; set; }
        public Nullable<int> IsPrintAddress { get; set; }
        public string RefAdd { get; set; }
    }
}
