//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_ContactSubCategoryTransaction
    {
        public int ContactSubCategoryTraID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public Nullable<int> ID { get; set; }
        public string TableName { get; set; }
    }
}
