//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPl_Document_CategoryDocument
    {
        public int DocumentID { get; set; }
        public string DocumentName { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual SIPL_DocumentCategory SIPL_DocumentCategory { get; set; }
    }
}
