//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_QuotationCarrier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIPL_QuotationCarrier()
        {
            this.SIPL_QuotationContainerRate = new HashSet<SIPL_QuotationContainerRate>();
            this.SIPL_QuotationRate = new HashSet<SIPL_QuotationRate>();
        }
    
        public decimal QuotationCarrierID { get; set; }
        public int fkCarrierID { get; set; }
        public decimal fkQuotationID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool Selected { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> ApprovedForBooking { get; set; }
        public string TransitTime { get; set; }
        public string Frequency { get; set; }
    
        public virtual SIPL_Quotation SIPL_Quotation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_QuotationContainerRate> SIPL_QuotationContainerRate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_QuotationRate> SIPL_QuotationRate { get; set; }
    }
}
