//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_ContractSheet
    {
        public decimal ContractSheetID { get; set; }
        public int ContractID { get; set; }
        public string Origin { get; set; }
        public Nullable<int> OriginID { get; set; }
        public string Des { get; set; }
        public Nullable<int> DesID { get; set; }
        public string PG { get; set; }
        public Nullable<int> PGID { get; set; }
        public string CG { get; set; }
        public Nullable<int> CGID { get; set; }
        public string Charge { get; set; }
        public Nullable<int> ChargeID { get; set; }
        public string D20DR { get; set; }
        public string D40DR { get; set; }
        public string D40HD { get; set; }
        public string D20OP { get; set; }
        public string D45 { get; set; }
        public string NonApp { get; set; }
        public Nullable<int> NonAppID { get; set; }
        public string App { get; set; }
        public Nullable<int> AppID { get; set; }
        public Nullable<System.DateTime> EffectFrom { get; set; }
        public Nullable<System.DateTime> ExpireOn { get; set; }
        public string Mode { get; set; }
        public string Route { get; set; }
        public string Type { get; set; }
        public string Remarks { get; set; }
    }
}
