//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class SIPL_ArrivalNoticeFreight
    {
      [Key]
        public decimal ArrivalNoticeFreightID { get; set; }
        public int CommonID { get; set; }
        public string InvoicNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string HouseBLNo { get; set; }
        public string ImportHouseDocNo { get; set; }
        public string ImportManifestNo { get; set; }
        public string AMSRefNo { get; set; }
        public string ExportManifestNo { get; set; }
        public string MasterBLNo { get; set; }
        public Nullable<System.DateTime> LastFreeDate { get; set; }
        public Nullable<System.DateTime> GODate { get; set; }
        public string ITNO { get; set; }
        public Nullable<System.DateTime> ITDate { get; set; }
        public string ITCity { get; set; }
        public string ITDestination { get; set; }
        public string DeliveryMode { get; set; }
        public string PickUpNO { get; set; }
        public string FreightLocation { get; set; }
        public string ContainerReturnDepot { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> FreightPrepaid { get; set; }
        public Nullable<bool> OriginalBill { get; set; }
        public Nullable<double> StrippingCharges { get; set; }
        public Nullable<double> PicrPass { get; set; }
        public Nullable<double> CleanTruckFee { get; set; }
        public Nullable<double> ISFFiling { get; set; }
        public Nullable<double> DDC { get; set; }
        public Nullable<double> TurnoverFee { get; set; }
        public Nullable<int> AFConsigneeID { get; set; }
        public Nullable<int> BrokerID { get; set; }
        public string FileNo { get; set; }
        public string TableType { get; set; }
        public string ReleasedBy { get; set; }
        public Nullable<System.DateTime> ReleasedDate { get; set; }
        public Nullable<int> Applyto { get; set; }
        public string LoadNo { get; set; }
    }
}
