//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_EnquiryServiceRequiredRORO
    {
        public decimal ROROID { get; set; }
        public decimal fkEnquiryID { get; set; }
        public Nullable<int> fkServiceRequiredID { get; set; }
        public Nullable<int> NoofCrans { get; set; }
        public Nullable<double> VolumeInCB { get; set; }
        public Nullable<double> VolumeInCF { get; set; }
        public Nullable<double> WeightInKG { get; set; }
        public Nullable<double> WeightInLBS { get; set; }
        public Nullable<bool> Inland { get; set; }
        public string InlandRemarks { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<double> MafiCharges { get; set; }
    
        public virtual SIPL_Enquiry SIPL_Enquiry { get; set; }
        public virtual SIPL_EnquiryServiceRequiredRORO SIPL_EnquiryServiceRequiredRORO1 { get; set; }
        public virtual SIPL_EnquiryServiceRequiredRORO SIPL_EnquiryServiceRequiredRORO2 { get; set; }
    }
}
