//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_ContractSpecification
    {
        public int SpecificationID { get; set; }
        public Nullable<int> fkHeadingNoteID { get; set; }
        public Nullable<int> fkContractID { get; set; }
        public string Detail { get; set; }
        public string FreeTime { get; set; }
    
        public virtual SIPL_ContractShipline SIPL_ContractShipline { get; set; }
        public virtual SIPL_HeadingNote SIPL_HeadingNote { get; set; }
    }
}
