//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_ContractCommodity
    {
        public int CCID { get; set; }
        public int CommodityId { get; set; }
        public decimal ContractID { get; set; }
        public int RouteId { get; set; }
        public int CommodityTypeID { get; set; }
        public Nullable<double> CommodityBasicRate { get; set; }
        public Nullable<double> CommoditySurcharge { get; set; }
        public string Remarks { get; set; }
    }
}
