//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_QuotationCharges
    {
        public int QuotaionChargeID { get; set; }
        public decimal fkQuoationID { get; set; }
        public Nullable<int> fkShipLineID { get; set; }
        public string D20DR { get; set; }
        public string D40DR { get; set; }
        public string D40HD { get; set; }
        public string D45 { get; set; }
        public string D20OP { get; set; }
        public string TotalD20DR { get; set; }
        public string TotalD40DR { get; set; }
        public string TotalD40HD { get; set; }
        public string TotalD45 { get; set; }
        public string TotalD20OP { get; set; }
        public string Margin { get; set; }
        public Nullable<bool> IsBooked { get; set; }
    
        public virtual SIPL_Quotation SIPL_Quotation { get; set; }
    }
}
