//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_ContractShipline
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIPL_ContractShipline()
        {
            this.SIPL_ContractApplicableCharges = new HashSet<SIPL_ContractApplicableCharges>();
            this.SIPL_ContractCommodityGroup = new HashSet<SIPL_ContractCommodityGroup>();
            this.SIPL_ContractContainer = new HashSet<SIPL_ContractContainer>();
            this.SIPL_ContractNonApplicable = new HashSet<SIPL_ContractNonApplicable>();
            this.SIPL_ContractPortGroup = new HashSet<SIPL_ContractPortGroup>();
            this.SIPL_ContractTradeService = new HashSet<SIPL_ContractTradeService>();
            this.SIPL_ContractSpecification = new HashSet<SIPL_ContractSpecification>();
        }
    
        public int ContractID { get; set; }
        public string ContractNo { get; set; }
        public string GALNo { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public Nullable<int> MQCID { get; set; }
        public Nullable<int> MQCQty { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int ShiplineID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual SIPL_Contact SIPL_Contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_ContractApplicableCharges> SIPL_ContractApplicableCharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_ContractCommodityGroup> SIPL_ContractCommodityGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_ContractContainer> SIPL_ContractContainer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_ContractNonApplicable> SIPL_ContractNonApplicable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_ContractPortGroup> SIPL_ContractPortGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_ContractTradeService> SIPL_ContractTradeService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_ContractSpecification> SIPL_ContractSpecification { get; set; }
    }
}
