//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_ShippingLine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIPL_ShippingLine()
        {
            this.SIPL_ShipLineTSSurCharges = new HashSet<SIPL_ShipLineTSSurCharges>();
            this.SIPL_ShippingLineRate = new HashSet<SIPL_ShippingLineRate>();
            this.SIPL_TSChargesConfigurator = new HashSet<SIPL_TSChargesConfigurator>();
        }
    
        public int ShippingLineId { get; set; }
        public string ShippingLineName { get; set; }
        public Nullable<int> fkCityID { get; set; }
        public Nullable<int> fkStateID { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string ContactNo { get; set; }
        public string EmailID { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> Flag { get; set; }
    
        public virtual SIPL_City SIPL_City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_ShipLineTSSurCharges> SIPL_ShipLineTSSurCharges { get; set; }
        public virtual SIPL_State SIPL_State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_ShippingLineRate> SIPL_ShippingLineRate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_TSChargesConfigurator> SIPL_TSChargesConfigurator { get; set; }
    }
}
