//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_OceanOD
    {
        public int OceanODID { get; set; }
        public int OceanID { get; set; }
        public string Marks { get; set; }
        public string Commodity { get; set; }
        public string Pcs { get; set; }
        public string Weight { get; set; }
        public string Volume { get; set; }
        public string ConsigneeID { get; set; }
        public Nullable<int> ShipperID { get; set; }
    
        public virtual SIPL_OceanCargo SIPL_OceanCargo { get; set; }
    }
}
