//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class SIPL_BookingStatusOld
    {
        [Key]
        public int StatusID { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
