//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_FollowUpDateEntry
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public Nullable<int> fkMailID { get; set; }
    
        public virtual SIPL_MarketingMail SIPL_MarketingMail { get; set; }
        public virtual SIPL_MarketingMail SIPL_MarketingMail1 { get; set; }
    }
}
