//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_EnquiryContainerType
    {
        public decimal EnquiryContainerTypeId { get; set; }
        public Nullable<decimal> fkEnquiryId { get; set; }
        public Nullable<int> fkContainerSizeId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual SIPL_ContainerSize SIPL_ContainerSize { get; set; }
        public virtual SIPL_ContainerType SIPL_ContainerType { get; set; }
    }
}
