//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_DeliveryOrder
    {
        public int DOID { get; set; }
        public string CommonID { get; set; }
        public string FileNo { get; set; }
        public Nullable<int> ExporterID { get; set; }
        public string DocumentNumber { get; set; }
        public string BLNumber { get; set; }
        public string FTZNumber { get; set; }
        public string ExportRef { get; set; }
        public Nullable<int> ConsignedTo { get; set; }
        public Nullable<int> FwdAgent { get; set; }
        public Nullable<int> ConsigneeID { get; set; }
        public string ExportInstruction { get; set; }
        public string CarriageBy { get; set; }
        public string PlaceOfReceiptID { get; set; }
        public string LandingPortID { get; set; }
        public string LoadingPert { get; set; }
        public string ForeignPortID { get; set; }
        public string MoveType { get; set; }
        public Nullable<int> Transshipment { get; set; }
        public string Voyage { get; set; }
        public string Vessel { get; set; }
        public string DeliveredBy { get; set; }
        public string Booking { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<System.DateTime> CutOFF { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public string EmptyPickup { get; set; }
        public Nullable<int> CheckedBY { get; set; }
        public string FULLRETURN { get; set; }
        public Nullable<System.DateTime> ISSUED { get; set; }
        public Nullable<int> UpdateID { get; set; }
        public string ExporterAddress { get; set; }
        public Nullable<bool> Isshipper { get; set; }
        public string ConsignedToType { get; set; }
        public Nullable<int> IsPrintAddress { get; set; }
        public string refAdd { get; set; }
        public string free_text { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
