//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_QuotationSurcharesRate
    {
        public decimal QuotationChargesRateID { get; set; }
        public decimal fkQuotationContainerRateID { get; set; }
        public int fkSurchargesID { get; set; }
        public double BuyingRate { get; set; }
        public double SellingRate { get; set; }
        public Nullable<bool> Isapplicable { get; set; }
        public Nullable<bool> IsChecked { get; set; }
    
        public virtual SIPL_QuotationContainerRate SIPL_QuotationContainerRate { get; set; }
        public virtual SIPL_TradeService SIPL_TradeService { get; set; }
    }
}
