//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_Document
    {
        public int DocumentID { get; set; }
        public string DocumentName { get; set; }
        public string DocContent { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> fkCategoryID { get; set; }
        public string InsertType { get; set; }
        public string FileName { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
