//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_ContractTradeService
    {
        public int ID { get; set; }
        public int fkTradeServiceID { get; set; }
        public int fkContractID { get; set; }
    
        public virtual SIPL_ContractShipline SIPL_ContractShipline { get; set; }
        public virtual SIPL_TradeService SIPL_TradeService { get; set; }
    }
}
