//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_QuotationRate
    {
        public decimal QuotationRateID { get; set; }
        public decimal fkQuotationCarrierID { get; set; }
        public decimal fkContainerID { get; set; }
        public decimal fkSurchargesID { get; set; }
        public double BuyingRate { get; set; }
        public double SellingRate { get; set; }
    
        public virtual SIPL_QuotationCarrier SIPL_QuotationCarrier { get; set; }
    }
}
