//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPL_ContractCarrier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIPL_ContractCarrier()
        {
            this.SIPL_ContractSurcharge = new HashSet<SIPL_ContractSurcharge>();
        }
    
        public decimal ContractCarrierID { get; set; }
        public decimal fkContractID { get; set; }
        public int fkCarrierID { get; set; }
    
        public virtual SIPL_Contact SIPL_Contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPL_ContractSurcharge> SIPL_ContractSurcharge { get; set; }
    }
}
