//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempSIPL_NextActionDue
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> NextActionDate { get; set; }
        public string Remarks { get; set; }
        public string RefID { get; set; }
        public string Type { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
