//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserwiseRolePermission
    {
        public int UserPermissionID { get; set; }
        public int UserId { get; set; }
        public int RoleId { get; set; }
        public int MenuGenerationID { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual SIPL_User SIPL_User { get; set; }
    }
}
