//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Address
    {
        public string Address { get; set; }
        public string CompanyName { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string TelNo { get; set; }
        public int ContactID { get; set; }
        public Nullable<int> StateID { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string Fulladdress { get; set; }
    }
}
