//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ContactMapping
    {
        public string Supplier { get; set; }
        public string SupplierCategory { get; set; }
        public string Shipper { get; set; }
        public string ShipperCategory { get; set; }
        public Nullable<int> SupplierRepID { get; set; }
        public string SupplierRep { get; set; }
        public Nullable<int> ShipperRepID { get; set; }
        public string ShipperRep { get; set; }
        public string SupplierCategoryID { get; set; }
        public string ShipperCategoryID { get; set; }
        public int ShipperID { get; set; }
        public int SupplierID { get; set; }
    }
}
