//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SIPL_Contact
    {
        public int ContactID { get; set; }
        public string CompanyName { get; set; }
        public string TelNo { get; set; }
        public string Address { get; set; }
        public string MobNo { get; set; }
        public string Fax { get; set; }
        public string WebSite { get; set; }
        public Nullable<int> CityID { get; set; }
        public string ContactPerson { get; set; }
        public string TaxID { get; set; }
        public string Email { get; set; }
        public string ZipCode { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> Flag { get; set; }
        public string AccountDetail { get; set; }
        public string AccountNo { get; set; }
        public string CustomerCode { get; set; }
        public string ContactCategoryID { get; set; }
        public string CityName { get; set; }
    }
}
