//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMGL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SIPL_ServiceReference
    {
        public decimal ServiceRefID { get; set; }
        public int fkServiceRequiredID { get; set; }
        public int RefID { get; set; }
        public string RefType { get; set; }
        public int IsDeleted { get; set; }
        public Nullable<int> fkContainerTypeID { get; set; }
        public string Name { get; set; }
        public Nullable<int> NoofContainer { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
